kernel/hwmon-max6697: 6.12: fix missing dependency
Add missing depends kmod-regmap-i2c.

ERROR: modpost: "__regmap_init_i2c" [drivers/hwmon/max6697.ko] undefined!

Ref: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.12.y&id=3a2a8cc3fe24ec48a3d222f5b9db68a3404ffab3

Signed-off-by: Mieczyslaw Nalewaj <namiltd@yahoo.com>
Link: https://github.com/openwrt/openwrt/pull/16547
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>